name: social_media_app
description: A social media app using Flutter, Dart, GetX, and REST API that allows users to share their photos and videos.

publish_to: "none"

version: 1.0.1+30

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  device_info_plus: ^8.0.0
  package_info_plus: ^3.0.2
  geolocator: ^9.0.2
  geocoding: ^2.0.5

  talker_flutter: ^2.2.1

  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  photo_view: ^0.14.0
  cached_network_image: ^3.2.3
  flutter_carousel_widget: ^2.0.1

  flutter_animate: ^2.1.0
  rive: ^0.10.1

  connectivity_plus: ^3.0.2
  http: ^0.13.5
  intl: ^0.18.0
  get_time_ago: ^1.2.1

  cloudinary: ^1.1.0
  r_upgrade: ^0.4.1

  libsignal_protocol_dart: ^0.6.5

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  url_launcher: ^6.1.7
  flutter_linkify: ^5.0.2
  share_plus: ^6.3.0

  flutter_local_notifications: ^13.0.0
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1

  better_player: ^0.0.83
  emoji_picker_flutter: ^1.5.2
  path: ^1.8.2
  file_picker: ^5.2.5
  path_provider: ^2.0.11
  flutter_markdown: ^0.6.13
  flutter_image_compress: ^1.1.3
  video_compress_ds: ^3.1.6

  flutter_screenutil: ^5.6.0
  permission_handler: ^10.2.0
  flutter_datetime_picker: ^1.5.1

  get: ^4.6.5
  get_storage: ^2.0.3
  built_value: ^8.4.3
  json_annotation: ^4.7.0
  equatable: ^2.0.5
  copy_with_extension: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16

  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  json_serializable: ^6.5.4
  copy_with_extension_gen: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/rive/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 200
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic

    - family: Muge
      fonts:
        - asset: assets/fonts/MugeRegular.ttf
